<?php
    // connenction file to database...
    include 'connect.php';
    include 'error.php';
    // directories.....
    $tpl        = 'includes/templates/'; // templates directory...
    $funcs      = 'includes/functions/'; // functions directory...
    $css        = 'layout/css/'; // css directory...
    $js         = 'layout/js/'; // javaScrpit directory...
    
    // include header
    include $tpl.'header.php';
    // include functions folder...
    include $funcs.'functions.php';
    
    //include navbar only in pages without $nonavbar varaible....
    if (!isset($noNavbar)){
        include $tpl.'navbar.php';
    }
?>